### PR TITLE
Generic Derived opaque type for given priority

### PR DESCRIPTION
**Pull request by joroKr21**
cc @bplommer - it doesn't work with invariant `OrElse` either 🤔

### CODE REVIEW

**Comment by bplommer** [comment]
Opaque types don't seem to behave how you'd expect with respect to variance - this compiles:

```scala
opaque type Foo[A] = A
object Foo:
  def apply[A](a: A): Foo[A] = a

val a: Foo[1] = Foo(1)
val b: Foo[Int] = a
```
Changing `Foo[A]` to `Foo[-A]` also makes no difference

**Comment by joroKr21** [comment]
I think this finally works

**Review by TimWSpence — APPROVED** [review]
This is pretty neat!

So the `summonFrom` in `OrInstances`  is how we assign precedent to existing instances over derived ones?

**Comment by joroKr21** [comment]
> So the summonFrom in OrInstances is how we assign precedent to existing instances over derived ones?

exactly 👍

**Pull request merged**
