### PR TITLE
Fix libraryDependencies for scala.js

### PR DESCRIPTION
**Pull request by Taig**
The dependencies are not properly referenced for scalajs causing linking errors

### CODE REVIEW

**Comment by joroKr21** [comment]
Huh, I wonder how it was working before :thinking: 

You need to update `EmptySuite`, looks like `scala.js` throws a different exception type.

**Comment by Taig** [comment]
Ah, I thought that was a flaky or something. I'll update the PR soon.

**Comment by Taig** [comment]
Tests work fine on my machine™. I'll try to find out what's going wrong here.

**Comment by joroKr21** [comment]
As far as I could see on Travis the test that expects a StackOverflow doesn't pass on scala.js because the exception type is different. I don't know anything about exceptions in scala.js

**Comment by Taig** [comment]
I tried to avoid platform specific code. Let me know if you'd rather have another approach.

**Comment by joroKr21** [comment]
Thanks, it would probably just be enough to expect any exception, this is quite the corner case, but it's also LGTM as it is.

**Comment by joroKr21** [comment]
I'm hesitant to merge this because the build now takes forever. Also running `test` locally is too slow. I guess now we have the problem of too many tests :smile: 

@kailuowang, @LukaJCB WDYT?

**Comment by kailuowang** [comment]
So just the confirm my understanding: the build didn't catch the scalajs link error and didn't run scalajs tests? The build takes a lot longer now because it's running tests on scalajs?

**Comment by joroKr21** [comment]
Yes I think that's exactly the case. Very odd.

**Comment by kailuowang** [comment]
I hope we can fix the build so that scalajs link error in the future would be captured, in case we introduce another dependency and use the wrong setting (`%%` instead of `%%%`), but I guess that we can do that in another PR. 
For this one I am not sure if we should merge as is either. 
We should try use a different settings on scalajs settings. 
One quick thing to try is to use the [TestSettings in Cats](https://github.com/typelevel/cats/blob/master/testkit/src/main/scala/cats/tests/CatsSuite.scala#L16-L28), it's readly available through `cats-testkit`

**Comment by joroKr21** [comment]
@Taig I hope you don't mind, I squashed your commits and added one commit to use `TestSettings` from Cats which reduce the build time significantly.

**Comment by joroKr21** [comment]
Looks good now, thanks @Taig!

**Comment by Taig** [comment]
👍 Do you have any further reading on why that change reduces build times so significantly?

**Comment by joroKr21** [comment]
JavaScript is slow :smile: take a look at the settings, everything is dialled down for Scala.js:
```scala
    PropertyCheckConfiguration(
      minSuccessful = if (Platform.isJvm) PosInt(50) else PosInt(5),
      maxDiscardedFactor = if (Platform.isJvm) PosZDouble(5.0) else PosZDouble(50.0),
      minSize = PosZInt(0),
      sizeRange = if (Platform.isJvm) PosZInt(10) else PosZInt(5),
      workers = if (Platform.isJvm) PosInt(2) else PosInt(1)
    )
```

**Pull request merged**
