### PR TITLE
Setup scalafmt

### PR DESCRIPTION
**Pull request by joroKr21**

### CODE REVIEW

**Comment by jatcwang** [comment]
Hi @joroKr21, I'm planning to switch this over to github actions. Do you think we can get this in before I start to avoid the merge conflicts? (and I see you've already done some of the necessary upgrades such as sbt 1.4). Thanks :)

**Comment by joroKr21** [comment]
Something's wrong with the `validate` command though - it's not working

**Comment by joroKr21** [comment]
@jatcwang done ✅ Thanks for picking this up! There is also #248 but we can ignore it because I would rather start from scratch on top of GitHub actions.

**Comment by jatcwang** [comment]
Thanks @joroKr21

**Pull request merged**
