### PR TITLE
Switch to github actions using sbt-github-actions

### PR DESCRIPTION
**Pull request by jatcwang**
Release step aren't setup as I don't have access to the repo secrets to test them

### CODE REVIEW

**Comment by jatcwang** [comment]
@joroKr21 Not sure if workflow needs to be manually activated in repo settings or only activates when merged?

**Comment by joroKr21** [comment]
I'm not sure either 🤔 maybe it has to be merged first.

**Comment by jatcwang** [comment]
Probably a security thing. Only one way to find out :smiling_imp:

**Comment by larsrh** [comment]
Thanks!

**Pull request merged**
