### PR TITLE
Improve implicitNotFound messages

### LINKED ISSUE #89: Improve @implicitNotFound error messages
I copied the code from documentation and replaced Show with Eq:
```
import cats._

case class A(a: Int)

object Test {
  implicit val eq: Eq[A] = {
    import derived.auto.eq._
    derived.semi.eq
  }
}
```
Compiled with Scala 2.12.4 (https://scastie.scala-lang.org/z4Ksxl4lR26ECCDjmGSAxQ)
```
Adaptation of argument list by inserting () is deprecated: this is unlikely to be what you want.
        signature: OrElse.primary[A, B](implicit a: A): shapeless.OrElse[A,B]
  given arguments: 
 after adaptation: OrElse.primary((): Unit)

ambiguous implicit values:
 both value mkEqHnil in class MkEqDerivation of type => cats.derived.MkEq[shapeless.HNil]
 and value mkEqCnil in class MkEqDerivation of type => cats.derived.MkEq[shapeless.CNil]
 match expected type cats.derived.MkEq[A]

could not find implicit value for parameter ev: cats.derived.MkEq[A]

not enough arguments for method eq: (implicit ev: cats.derived.MkEq[A])cats.Eq[A].
Unspecified value parameter ev.
```

### PR DESCRIPTION
**Pull request by joroKr21**
Putting this up for discussion. How exactly should we format and formulate the messages?

Current proposal:
  * One sentence to mention what exactly was not derived
  * One sentence to introduce a list of conditions
  * List the conditions, one of which must be satisfied

~Also: should we use kind-projector syntax or not?~

Closes #89

### CODE REVIEW

**Comment by kailuowang** [comment]
@joroKr21 that proposed message looks very help to me. 
I don't have a strong opinion on whether we should use kind-projector syntax. I am thinking maybe using the syntax but with a quick note linking to kind-projector would be helpful.

**Comment by joroKr21** [comment]
@kailuowang what did you mean by that:
> that proposed message looks very help to me

**Comment by kailuowang** [comment]
sorry @joroKr21, I meant "very helpful". was on my phone.

**Comment by joroKr21** [comment]
@kailuowang how does it look now?

**Comment by kailuowang** [comment]
Lgtm!

**Comment by joroKr21** [comment]
@kailuowang updated all typeclass derivations. Don't know if we can think of better messages for things that are not typeclasses.

**Pull request merged**
