### PR TITLE
Fix semigroup hierarchy derivation for recursive types

### PR DESCRIPTION
**Pull request by TimWSpence**
Fix semigroup hierarchy derivation for recursive types

### CODE REVIEW

**Comment by joroKr21** [comment]
@TimWSpence did the CI hang? I try to cancel it but it doesn't work. I think this is blocked on typelevel/shapeless-3#40

**Comment by TimWSpence** [comment]
🤦 thanks @joroKr21, I think I did see that issue and then completely forgot about it. I'll have a proper look through it later

**Review by joroKr21 — APPROVED** [review]
I think we should give the same treatment to all product instances

**Comment by joroKr21** [comment]
Oh no I think it's still hanging 🤔

**Comment by joroKr21** [comment]
Superseded by #455

**Pull request closed without merging**
