### PR TITLE
Upgrade to Scala 3.2

### PR DESCRIPTION
**Pull request by TimWSpence**
Contains a load of fixes that we need, particularly for Mirror synthesis

### CODE REVIEW

**Comment by joroKr21** [comment]
You need to run `githubWorkflowGenerate`

**Comment by TimWSpence** [comment]
> You need to run `githubWorkflowGenerate`

Sorry, forgot to check the build before I logged off yesterday 🤦

**Comment by joroKr21** [comment]
> Does scala native not support 3.2 yet?

I think the version that supports is 0.4.7
We should really merge this branch to `master` and release it soon.
Is there something still missing? I guess more tests with enums 🤔

**Review by joroKr21 — APPROVED** [review]

**Comment by TimWSpence** [comment]
@joroKr21 thanks for fixing the rest of the dependencies! Sorry I hadn't got round to it yet

**Comment by joroKr21** [comment]
> @joroKr21 thanks for fixing the rest of the dependencies! Sorry I hadn't got round to it yet

No worries, I was thinking if we should force the update to 3.2 but I think with all the bugs around mirrors we really should.

**Comment by TimWSpence** [comment]
> > @joroKr21 thanks for fixing the rest of the dependencies! Sorry I hadn't got round to it yet
> 
> No worries, I was thinking if we should force the update to 3.2 but I think with all the bugs around mirrors we really should.

Yeah I think so too. https://www.scala-lang.org/blog/2022/08/17/long-term-compatibility-plans.html seems to recommend that everyone upgrade as well, although I don't know if people are following that advice in general. At some point should we move to sbt-typelevel to let it handle a lot of the build pain for us?

**Comment by joroKr21** [comment]
We are using `sbt-typelevel`

**Pull request merged**
