### PR TITLE
Bump Scala and Cats and comment out tests that don't work

### PR DESCRIPTION
**Pull request by joroKr21**

### CODE REVIEW

**Review by TimWSpence — APPROVED** [review]
Thanks for this! So many FIXMEs 😭 

We're just going to 3.1.0 now then and accepting the regressions for the moment?

**Comment by joroKr21** [comment]
> We're just going to 3.1.0 now then and accepting the regressions for the moment?

I don't see another choice - Scala native only works with 3.1 and there are other bug fixes we do want.
I think so far the problem is only with `Reducible` and `NonEmptyTraverse` which are not used that often.

**Comment by gvolpe** [comment]
@joroKr21 think we can get another milestone published including these fixes? 🙏🏽

**Comment by joroKr21** [comment]
Yes, I think just pushing a tag should do it - let me do that today

**Pull request merged**
